---
name: MooseX-StrictConstructor
version: 0.06_02
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Make your object constructors blow up on unknown attributes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Moose: 0.55_04
  Test::More: 0
provides:
  MooseX::StrictConstructor:
    file: lib/MooseX/StrictConstructor.pm
    version: 0.06_02
  MooseX::StrictConstructor::Role::Meta::Method::Constructor:
    file: lib/MooseX/StrictConstructor/Role/Meta/Method/Constructor.pm
  MooseX::StrictConstructor::Role::Object:
    file: lib/MooseX/StrictConstructor/Role/Object.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
