---
name: MooseX-StrictConstructor
version: 0.01
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Make your object constructors blow up on unknown attributes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  MooseX::Object::StrictConstructor:
    file: lib/MooseX/Object/StrictConstructor.pm
  MooseX::StrictConstructor:
    file: lib/MooseX/StrictConstructor.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
