---
name: MooseX-StrictConstructor
version: 0.03
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Make your object constructors blow up on unknown attributes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Moose: 0.26
  Test::More: 0
provides:
  MooseX::Object::StrictConstructor:
    file: lib/MooseX/Object/StrictConstructor.pm
  MooseX::StrictConstructor:
    file: lib/MooseX/StrictConstructor.pm
    version: 0.03
  MooseX::StrictConstructor::Meta::Class:
    file: lib/MooseX/StrictConstructor/Meta/Class.pm
  MooseX::StrictConstructor::Meta::Method::Constructor:
    file: lib/MooseX/StrictConstructor/Meta/Method/Constructor.pm
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
